### ISSUE TITLE
`make` fails at result presentation step

### ISSUE THREAD

**Issue by naikrovek** [PlummersSoftwareLLC/Primes#396]
For the third time now, I've run `make` and have had all the benchmarks run just fine only for the entire operation to fail at the point where the presentation of the results happens.

I see this error from node:
```
> ts-node ./src/index.ts "report" "-d" "/tmp/tmp.3PxYmVnGws" "-f" "table"

(node:30699) UnhandledPromiseRejectionWarning: TypeError: glob_1.default.sync(...).flatMap is not a function
    at Command.exports.command.commander_1.Command.requiredOption.option.action (/home/jjohnson/Primes/tools/src/commands/report.ts:26:62)
    at Command.listener [as _actionHandler] (/home/jjohnson/Primes/tools/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/home/jjohnson/Primes/tools/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/home/jjohnson/Primes/tools/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/home/jjohnson/Primes/tools/node_modules/commander/index.js:1460:12)
    at Command.parse (/home/jjohnson/Primes/tools/node_modules/commander/index.js:1292:10)
    at Object.<anonymous> (/home/jjohnson/Primes/tools/src/index.ts:9:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/jjohnson/Primes/tools/node_modules/ts-node/src/index.ts:1295:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
(node:30699) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30699) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't know enough about TypeScript to fix this, or this would be a pull request instead of a bug report.

The very first time I ran this, it worked perfectly.  A later run the same day produced this error.  Today I ran `make` again and this error arose again, then I deleted the `Primes` directory, re-cloned, and re-ran yet again and that is the error that I have pasted here.

If this is something that I am somehow doing wrong, please let me know.

**Comment by naikrovek** [comment]
Oooh, I think this is because I forgot to add the correct version of Node to the PATH env var before running `make`.

**Comment by marghidanu** [comment]
Please follow the installation instructions and make sure you have at least node 10 installed on your machine.

**Comment by naikrovek** [comment]
Node 10 was producing the error message in the bug report.  Node 14 doesn't, and I'm expecting Node 16 to also work just fine.
